services:
  mysql:
    container_name: rawgdb
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: rawgDatabase
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}